# 配置文件请严格遵循yaml语法格式，yaml学习地址:
#  https://ansible-tran.readthedocs.io/en/latest/docs/YAMLSyntax.html
#  http://einverne.github.io/post/2015/08/yaml.html

# 定时时间、
alarm_timed: '00:30'

# 格言渠道
# 1 : ONE●一个
# 2 : 词霸（每日英语）
dictum_channel: 2

girlfriend_infos:
  -
    #女友微信昵称
    wechat_name: '小灰Air'
    #女友所在桂林
    city_name: '深圳'
    # 从那天开始勾搭的（可空）
#    start_date: '2019-6-6'
    # 短句的最后留言（可空）
    sweet_words: '--来自Lance的小助手'

  #如果有你多个人需要发送，则参照这个样式，复制即可
#  -
#    wechat_name: '陈老师'
#    city_name: '朝阳区'
#    start_date: '2018-11-11'
#    sweet_words: '来自你俊美的老公。'



